name: Danger

on:
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Base
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Build CDN (Base)
        run: |
          npm ci
          npm run build-cdn
          mv build base_build

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Build CDN (PR)
        run: |
          npm ci
          npm run build-cdn

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
