name: Danger

on:
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          path: pr

      - name: Checkout Base
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Build CDN (PR)
        run: |
          npm ci
          npm run build-cdn
        working-directory: pr

      - name: Build CDN (Base)
        run: |
          npm ci
          npm run build-cdn
        working-directory: base

      - name: Copy Base Build
        run: cp -R base/build pr/build_base

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: pr
