name: Danger

on:
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Base
        uses: actions/checkout@v3
        with:
          path: base
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          path: pr

      - name: Build CDN (Base)
        run: |
          npm ci
          npm run build-cdn
        working-directory: ./base

      - name: Build CDN (PR)
        run: |
          npm ci
          npm run build-cdn
        working-directory: ./pr

      - name: Copy Base
        run: cp -R ./base/build ./pr/build_base

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./pr
