name: Danger

on:
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Base
        uses: actions/checkout@v3
        with:
          path: base
          ref: ${{ github.base_ref }}

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          path: pr

      - name: Build CDN (Base)
        run: |
          npm ci
          npm run build-cdn
        working-directory: ./base

      - name: Build CDN (PR)
        run: |
          npm ci
          npm run build-cdn
        working-directory: ./pr

      - name: Copy Base
        run: cp -R ./base/build ./pr/build_base

      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./pr
